# Generated by Django 3.0.5 on 2020-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200406_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='lastName',
        ),
        migrations.AddField(
            model_name='mentee',
            name='name',
            field=models.CharField(default='mentee first name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='mentor first name', max_length=200, null=True),
        ),
    ]
