# Generated by Django 3.0.5 on 2020-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200406_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='motivation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentee',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentee',
            name='stream',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentor',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentor',
            name='street1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='street2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
