# Generated by Django 3.0.5 on 2020-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_mentor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='required_tools',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='suitable_for',
            field=models.CharField(choices=[('Bachlor', 'Bachelor'), ('Master', 'Master'), ('PHD', 'PHD')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(default='static/userpictures/picture.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
