# Generated by Django 3.0.5 on 2020-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200413_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='cover_photo',
            field=models.ImageField(default='static/userpictures/default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentor',
            name='cover_photo',
            field=models.ImageField(default='static/userpictures/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='photo',
            field=models.ImageField(default='static/userpictures/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(default='static/userpictures/default.jpg', null=True, upload_to=''),
        ),
    ]
