# Generated by Django 3.0.5 on 2020-04-13 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200413_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='cover_photo',
            field=models.ImageField(blank=True, default='static/userpictures/defaultcover.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='motivation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='photo',
            field=models.ImageField(blank=True, default='static/userpictures/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='stream',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='cover_photo',
            field=models.ImageField(blank=True, default='static/userpictures/defaultcover.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, default='static/userpictures/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='street1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
