# Generated by Django 3.0.5 on 2020-04-27 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_auto_20200414_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='menteefollowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentor',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='mentorfollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
